# Generated by Django 6.0.6 on 2026-07-06 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='Category',
            new_name='category',
        ),
    ]
