# Generated by Django 6.0.6 on 2026-07-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_exercise_dailylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='calories_burned',
        ),
        migrations.AddField(
            model_name='exercise',
            name='emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
