# Generated by Django 6.0.6 on 2026-07-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_exercise_calories_burned_exercise_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='meals',
            field=models.ManyToManyField(blank=True, to='pages.meal'),
        ),
    ]
